"$schema" = "./node_modules/wrangler/config-schema.json"
name = "portfolio"
main = "src/index.ts"
compatibility_date = "2026-04-08"

[vars]
APP_NAME = "Laravel"
APP_URL = "http://127.0.0.1:8787"
APP_DEBUG = "true"
SESSION_COOKIE_NAME = "laravel-session"
SESSION_TTL_MINUTES = "120"
COMMENTS_RATE_LIMIT_MAX = "5"
COMMENTS_RATE_LIMIT_WINDOW_SECONDS = "3600"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "3059bb2b-5719-454a-aeff-ef2d9461e0d2"
preview_database_id = "DB"
migrations_dir = "migrations"

